In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.19.4


In [4]:
arr = np.arange(20)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
arr = np.arange(2)

In [7]:
arr

array([0, 1])

In [8]:
np.full((1,1), True, dtype=bool)

array([[ True]])

In [10]:
np.full((5,5), False, dtype=bool)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [11]:
np.ones((2,2), dtype=bool)

array([[ True,  True],
       [ True,  True]])

In [13]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [14]:
arr = np.array([0, 1, 2, 3, 4, 5])

In [15]:
arr[arr % 5 == 1]

array([1])

In [16]:
arr[arr % 1 == 5]

array([], dtype=int32)

In [17]:
arr[arr % 1 == 1]

array([], dtype=int32)

In [18]:
arr[arr % 2 == 1]

array([1, 3, 5])

In [21]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [22]:
arr[arr %2 == 2] =-1

In [23]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr[arr % 2 == 1] = -1

In [25]:
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

In [26]:
arr = np.arange(20)
out = np.where(arr % 5 == 2, -4, arr)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [27]:
out

array([ 0,  1, -4,  3,  4,  5,  6, -4,  8,  9, 10, 11, -4, 13, 14, 15, 16,
       -4, 18, 19])

In [28]:
arr = np.arange(15)
arr.reshape(3, -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
arr.reshape(5, -2)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [30]:
arr.reshape(3, -2)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
arr.reshape(3, -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
a = np.arange(5).reshape(2,-1)
b = np.repeat(1, 5).reshape(2,-1)

ValueError: cannot reshape array of size 5 into shape (2,newaxis)

In [34]:
a = np.arange(15).reshape(2,-1)
b = np.repeat(1, 15).reshape(2,-1)

ValueError: cannot reshape array of size 15 into shape (2,newaxis)

In [35]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [36]:
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [38]:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [39]:
a = np.arange(20).reshape(2,-1)
b = np.repeat(1, 20).reshape(2,-1)

In [40]:
np.r_[a, b]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])

In [41]:
np.vstack([a, b])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])

In [42]:
a = np.arange(10).reshape(5,-1)
b = np.repeat(1, 10).reshape(5,-1)

In [43]:
np.c_[a,b]

array([[0, 1, 1, 1],
       [2, 3, 1, 1],
       [4, 5, 1, 1],
       [6, 7, 1, 1],
       [8, 9, 1, 1]])

In [44]:
a = np.array([1,2,3])`

SyntaxError: invalid syntax (<ipython-input-44-3982170e969a>, line 1)

In [45]:
np.r_[np.repeat(a, 3), np.tile(a, 3)]

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [46]:
a = np.array([1,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [50]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.array([9,7,5,3,1,7,4,7,4,7,0])
np.intersect1d(a,b,c)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [51]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.array([9,2,11,2,7,4,6,5,3,1,8])
np.intersect1d(a,b)

array([2, 4])

In [52]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [53]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [54]:
a = np.array([5,6,7,8,9])
b = np.array([1,2,3,4,5])

In [55]:
np.setdiff1d(a,b)

array([6, 7, 8, 9])

In [56]:
a = np.array([5,6,7,8,9])
b = np.array([5,6,7,8,9])

In [57]:
np.setdiff1d(a,b)

array([], dtype=int32)

In [58]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [59]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.array([1,2,3,4,5,6,7,8,9,0])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)