In [1]:
import numpy

In [2]:
import numpy as np

In [5]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
a.shape

(2, 5)

In [7]:
a.ndim

2

In [8]:
a.dtype.name

'int32'

In [9]:
a.itemsize

4

In [10]:
a.size

10

In [11]:
type(a)

numpy.ndarray

In [13]:
b = np.array([2, 3, 4])
b

array([2, 3, 4])

In [14]:
type(b)

numpy.ndarray

In [15]:
c = np.arange(50).reshape(5, 10)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [17]:
c.shape

(5, 10)

In [18]:
c.ndim

2

In [19]:
c.dtype.name

'int32'

In [20]:
c.itemsize

4

In [21]:
c.size

50

In [22]:
type(c)

numpy.ndarray

In [24]:
d  = np.array([5, 6, 7])
d

array([5, 6, 7])

In [26]:
type(d)

numpy.ndarray

In [27]:
print(np.arange(50000))

[    0     1     2 ... 49997 49998 49999]


In [28]:
print(np.arange(50000).reshape(500,100))

[[    0     1     2 ...    97    98    99]
 [  100   101   102 ...   197   198   199]
 [  200   201   202 ...   297   298   299]
 ...
 [49700 49701 49702 ... 49797 49798 49799]
 [49800 49801 49802 ... 49897 49898 49899]
 [49900 49901 49902 ... 49997 49998 49999]]


In [30]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [31]:
b = np.arange(24).reshape(6,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [32]:
c = np.arange(64).reshape(8,8)
print(c)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]


In [33]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [34]:
b = np.array([(1,3,5,7), (4,6,8)])
b

<ipython-input-34-f2ff206b4510>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  b = np.array([(1,3,5,7), (4,6,8)])


array([(1, 3, 5, 7), (4, 6, 8)], dtype=object)

In [36]:
c = np.array([(1.5,3,5), (4,6,8)])
c

array([[1.5, 3. , 5. ],
       [4. , 6. , 8. ]])

In [41]:
d = np.array([(1.5,2,3), (4,9,6)])
d

array([[1.5, 2. , 3. ],
       [4. , 9. , 6. ]])

In [42]:
e = np.array( [ [8,9], [1,2] ], dtype=complex )
e

array([[8.+0.j, 9.+0.j],
       [1.+0.j, 2.+0.j]])

In [43]:
np.zeros((10,20))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [44]:
np.ones( (1,3,5), dtype=np.int16 )

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

In [45]:
np.ones( (2,3,4), dtype=np.int32 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [46]:
np.ones( (5,5,5), dtype=np.int64 )

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int64)

In [47]:
np.empty( (2) ) 

array([7.17976793e-312, 0.00000000e+000])

In [48]:
np.empty( (9,1) ) 

array([[2.12199579e-314],
       [2.05833592e-312],
       [2.10077583e-312],
       [2.14321575e-312],
       [4.18033171e-312],
       [4.22277162e-312],
       [4.26521154e-312],
       [6.30232750e-312],
       [6.34476742e-312]])

In [49]:
np.arange(0,9,3)

array([0, 3, 6])

In [51]:
a = np.array( [2,3,4,5] )

In [65]:
b = np.arange(3)
b

array([0, 1, 2])

In [67]:
b**5

array([ 0,  1, 32], dtype=int32)

In [68]:
a<3

array([ True, False, False, False])

In [70]:
a = np.array( [7,8,9,10] )

In [71]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [72]:
c = a-b

In [73]:
c

array([7, 7, 7, 7])

In [74]:
b*9

array([ 0,  9, 18, 27])

In [75]:
a>9

array([False, False, False,  True])